### ISSUE TITLE
最新的vConsole@3.9.1的依赖会报错

### ISSUE THREAD

**Issue by champkeh** [Zhangstring/gesture-vconsole#1]
![image](https://user-images.githubusercontent.com/7316006/130388000-42971820-0676-4a00-b69e-705d4b97d1ea.png)

开发类似这样的包装工具时，是否把依赖的版本写死会更好呢？

**Comment by Zhangstring** [comment]
vConsole的问题，3.4.1以后版本在vConsole未初始化完成使用setOption会报这个错误。

**Comment by Zhangstring** [comment]
使用VConsole{option}的形式可以避免
